[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip"
]

[start]
cmd = "python app/bot.py"
